name: Build and Upload packages for release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags that start with 'v'

jobs:
  build-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run bash script
        run: sudo bash -x ./Contrib/release.sh
        env:
          ENV_VAR: value

      - name: Upload zips, tar.gz and deb
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ./packages/*  # Adjust the path to your generated files
          compression-level: 0
          if-no-files-found: error

      - name: Upload windows build
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ./build/win-x64  # Adjust the path to your generated files
          compression-level: 3
          if-no-files-found: error

  installer-for-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Install WiX Toolset
      run: |
        choco install wixtoolset --version=3.14.1 --force
      shell: powershell

    - name: Restore NuGet packages
      run: |
        dotnet restore WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
        dotnet build WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj --configuration Release --runtime win-x64 --force --output ./build --self-contained true --disable-parallel --no-cache --no-restore --property:SelfContained=true --property:VersionPrefix=2.1.0.1 --property:DebugType=none --property:DebugSymbols=false --property:ErrorReport=none --property:DocumentationFile='' --property:Deterministic=true

    - name: Build .wixproj
      run: |
        # Set the base path and version as variables
        export BASE_PATH="./build"
        export BUILD_VERSION="2.1.0.1"

        # Compile the .wxs file to .wixobj
        candle WalletWasabi.WindowsInstaller/*.wxs -dBasePath=$BASE_PATH -dBuildVersion=$BUILD_VERSION

        WIX_UI_EXTENSION_PATH=$(where candle.exe | head -n 1 | sed 's/candle.exe/WixUIExtension.dll/')
        WIX_UTIL_EXTENSION_PATH=$(where candle.exe | head -n 1 | sed 's/candle.exe/WixUtilExtension.dll/')

        # Link the .wixobj file to create the .msi installer
        light *.wixobj -loc WalletWasabi.WindowsInstaller/Common.wxl -ext $WIX_UI_EXTENSION_PATH -ext $WIX_UTIL_EXTENSION_PATH  -o installer.msi
      shell: bash

#  create-release:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Create GitHub Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          draft: false
#          prerelease: false
#
#      - name: Upload Release Asset
#        uses: actions/upload-release-asset@v1
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: path/to/generated/files/yourfile.ext  # Adjust the path and filename
#          asset_name: yourfile.ext
#          asset_content_type: application/octet-stream
#
