name: Build and Upload packages for release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags that start with 'v'

jobs:
  build-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run bash script
        run: sudo bash -x ./Contrib/release.sh
        env:
          ENV_VAR: value

      - name: Upload zips, tar.gz and deb
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ./packages/*  # Adjust the path to your generated files
          compression-level: 0
          if-no-files-found: error

      - name: Upload windows build
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ./build/win-x64  # Adjust the path to your generated files
          compression-level: 3
          if-no-files-found: error

  installer-for-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Install WiX Toolset
      run: |
        choco install wixtoolset --version=3.11.2
      shell: powershell

    - name: Restore NuGet packages
      run: |
        dotnet restore WalletWasabi.Fluent.Desktop.csproj

    - name: Build .wixproj
      run: |
        msbuild WalletWasabi.WindowsInstaller/WalletWasabi.WindowsInstaller.wixproj /p:Configuration=Release

#  create-release:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Create GitHub Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          draft: false
#          prerelease: false
#
#      - name: Upload Release Asset
#        uses: actions/upload-release-asset@v1
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: path/to/generated/files/yourfile.ext  # Adjust the path and filename
#          asset_name: yourfile.ext
#          asset_content_type: application/octet-stream
#
